[package]
name = "debversion"
version = "0.1.4"
edition = "2021"
authors = ["Jelmer Vernooĳ <jelmer@debian.org>"]
license = "Apache-2.0"
description = "Debian version parsing, manipulation and comparison"

[features]
default = []
sqlx = ["dep:sqlx"]

[dependencies]
lazy-regex = "3"
sqlx = { version = "0.6", optional = true, default-features = false, features = ["postgres"] }

[dev-dependencies]
sqlx = { version = "0.6", default-features = false, features = ["runtime-tokio-rustls"] }
