name: Rust

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - run: |
        python -m pip install python_debian
    - name: Build
      run: cargo build --verbose
    - name: Install cargo-all-features
      run: cargo install cargo-all-features
    - name: Run tests
      run: cargo test-all-features --verbose
